Allow vehicles that have built-in joystick support to also use QGC joystick functions.
mavlink/qgroundcontrol pull request #10106
Opened 2022-01-07 20:36 UTC by Williangalvani

This exposes some of QGC's built-in functions to these users, specifically for control of video streams.
The options are filtered so that there are no repeated functions (there are both firmware and QGC implementation for many of the functions).

This is the final result:
![joystick](https://user-images.githubusercontent.com/4013804/148603937-cde95d39-41a0-4b5b-9f80-da3a47df4c5d.gif)

Right now this only affects Sub.

2022-01-11 14:16 UTC, patrickelectric requested changes

2022-01-11 14:16 UTC, patrickelectric commented on src/VehicleSetup/JoystickConfigButtons.qml
> +                    property var qgcActions:    _activeJoystick.assignableActionTitles.filter(function(s){return s.includes("Camera") || s.includes("Stream") || s.includes("Zoom") || s.includes("Gimb
You could break this function in a new line to make it easier to read and maintain :laughing: 
```
property var qgcActions: _activeJoystick.assignableActionTitles.filter(function(string){
    return s.includes("Camera") \
        || s.includes("Stream") \
        || s.includes("Stream") \
        || s.includes("Zoom") \
        || s.includes("Gimbal") \
        || s.includes("No Action") \
    })
```

or

```
property var qgcActions: _activeJoystick.assignableActionTitles.filter(function(string){
    return [
        s.includes("Camera")
        , s.includes("Stream")
        , s.includes("Stream")
        , s.includes("Zoom")
        , s.includes("Gimbal")
        , s.includes("No Action")
    ].some(Boolean)})
```

2022-01-11 14:16 UTC, patrickelectric commented on src/VehicleSetup/JoystickConfigButtons.qml
> +                                var i = find(_activeJoystick.buttonActions[modelData])
this intermediary variable is a bit unnecessary, and currentIndex already provides the information that find will return an index like variable.

2022-01-11 14:16 UTC, patrickelectric commented on src/VehicleSetup/JoystickConfigButtons.qml
> +                    fact:       controller.parameterExists(-1, `BTN${index}_SFUNCTION`) ? controller.getParameterFact(-1, `BTN${index}_SFUNCTION`) : null;
Should we make a helper function to avoid maintaining this string around the code ?
The same thing for `BTN${INDEX}_FUNCTION`

2022-01-12 13:37 UTC, patrickelectric approved these changes

2022-01-12 13:37 UTC, merged

2022-11-11 15:27 UTC, junwoo091400 commented
Could you clarify what a FW action, and QGC action is? I have been browsing through the code and found it quite un-intuitive :thinking:

Is FW action, somehow related to component metadata or sth?

2022-11-11 15:42 UTC, Williangalvani commented
Hi,

That is an ArduSub peculiarity, I guess.
Ardusub has all these functions implemented in the firmware:
https://github.com/ArduPilot/ardupilot/blob/Sub-4.1/libraries/AP_JSButton/AP_JSButton.h#L11-L113
This means we just tell ArduSub "hey, button x is pressed" and ArduSub does whatever it wants with it. I called this a FW action in this code.

QGC Actions are handled by QGC. QGC can do things such as switching video streams and cameras, as well as sending MAVLink commands to the vehicle.

There is actually an overlap in these, but they are both useful for Sub, as QGC not able to control some Sub functionality with MAVLink, and ArduSub is unable to control video streams, for example.

I hope this was clear enough.