Fix Structure Scan Editor Layout
mavlink/qgroundcontrol pull request #10160
Opened 2022-02-10 19:14 UTC by holden-zenith

Fixes #10142

2022-02-15 10:19 UTC, gromain commented
There is an issue with the built AppImage.
Once a polygon is created after adding a structure scan pattern, the module content disappear.
It is correctly formatted while it's still visible though.

2022-02-20 13:56 UTC, gromain commented
@holden-zenith is there anything more on my side I could do to help?

2022-02-20 20:23 UTC, holden-zenith commented
> @holden-zenith is there anything more on my side I could do to help?

No, I'll take a look at it soon. I've been away

2022-02-22 16:20 UTC, patrickelectric requested changes

2022-02-22 16:20 UTC, patrickelectric commented on src/PlanView/StructureScanEditor.qml
> +        }*/
You can remove the code, it's not necessary to comment if it's not important.

2022-03-02 22:01 UTC, gromain commented
Works for me

2022-03-08 16:18 UTC, patrickelectric approved these changes

2022-03-08 16:19 UTC, merged

2022-03-08 16:19 UTC, mrpollo commented
thanks @holden-zenith