Use PX4 Board information metadata to identify board IDs
mavlink/qgroundcontrol pull request #10343
Opened 2022-07-13 15:36 UTC by junwoo091400

## Context
This is the QGC part of the PR: https://github.com/PX4/PX4-Autopilot/pull/19848
(To be written)

2022-07-21 14:58 UTC, junwoo091400 commented
Status updated in PX4 side: https://github.com/PX4/PX4-Autopilot/pull/19848#issuecomment-1191590296

2022-07-22 07:44 UTC, junwoo091400 commented
The PR diff looks big but actually the majority is from the Manifest file (1k+ lines added) :rofl:

2022-09-02 10:16 UTC, patrickelectric requested changes
I did a quick review, the patch is a bit big, but for general tips, some commits can be squashed and some of the code can be improved.

2022-09-02 10:16 UTC, patrickelectric commented on src/VehicleSetup/FirmwareUpgradeController.cc
> +    for (int board_idx = 0; board_idx < boardInfoArray.count(); board_idx++) {
`for(const auto& board: boardInfoArray)`

2022-09-02 10:16 UTC, patrickelectric commented on src/VehicleSetup/FirmwareUpgradeController.cc
> +        for (int build_variant_idx = 0; build_variant_idx < buildVariantsArray.count(); build_variant_idx++) {
`for(const auto& build_variant: buildVariantsArray)`

2024-01-03 00:19 UTC, DonLakeFlyer commented
Is this still being worked on?

2024-01-14 01:39 UTC, DonLakeFlyer commented
Not supported by mavlnk

2024-01-14 01:39 UTC, closed without merging