fix: check VIDEO_STREAM_STATUS messages whether stream is running
mavlink/qgroundcontrol pull request #10635
Opened 2023-03-23 23:17 UTC by RedFox20

I discovered this bug when trying to add integration support for a multi-camera mavlink device with multiple streams.

The current code assumed that each Camera would always be streaming, but this is not always the case, and not guaranteed by MAVLink camera protocol. Especially with 3+ cameras, due to data rate limitations only 1 out 3 might be active.

QGC would be stuck assuming that the streams are running, but the camera system could be expecting for a VIDEO_START_STREAMING command for those particular streams.

The VIDEO_STREAM_STATUS `flags` field describes whether the Stream is actually running, and updating the `_currentStream` value according to those flags re-enables video stream switching.

I also slightly improved the camera debug logging to make it easier to debug multi-camera system issues.

2023-04-07 16:41 UTC, patrickelectric requested changes

2023-04-07 16:41 UTC, patrickelectric commented on src/Camera/QGCCameraControl.cc
> +    if (stream != _currentStream && 0 <= stream && stream < _streamLabels.count()) {
you can just revert the logic, avoid the indentation level completely.

2023-04-07 16:41 UTC, patrickelectric commented on src/Camera/QGCCameraControl.cc
> +            }
you can use `std::find_if` and `std::distance`

2023-04-24 19:23 UTC, booo commented
@RedFox20 can you update the PR with the suggested changes?

2023-05-20 20:01 UTC, booo commented
@RedFox20 please reopen if you find the time to integrate the suggested changes. We would love to integrate your updated PR.

2023-05-20 20:01 UTC, closed without merging