3D View upgrade: Visualizing the world imagery in 3D View
mavlink/qgroundcontrol pull request #11214
Opened 2024-03-07 22:18 UTC by omid-esrafilian

The following changes have been made to the 3D View:

- World imagery corresponding to the .osm file is also visualized in the 3D View along with the buildings (the imagery data changes based on the map provider specified in the Application Settings -> Maps).
- The RTL is added to the 3D View
- The MapScale widget is not visible while the 3D View is open

An example of the new changes is illustrated in the figure below:

![Screenshot from 2024-03-07 22-55-36](https://github.com/mavlink/qgroundcontrol/assets/115142498/4ce9784d-fa4c-47b9-aead-d1621b719946)

2024-03-14 14:08 UTC, omid-esrafilian commented
@SebastianViollaz 
I don't see the changes I added to the code. 
Please note that the code has not been merged yet into **"master"**, so if you wish to have these changes, please make sure that you are using the branch **"3D_View_with_imagery "** of my GitHub repository.

2024-03-14 14:45 UTC, omid-esrafilian commented
@SebastianViollaz 
It is the same as building the QGC code. Please follow the following steps:

1) git clone --recursive -j8 https://github.com/omid-esrafilian/qgroundcontrol-viewer3D.git
2) cd qgroundcontrol-viewer3D
4) git checkout 3D_View_with_imagery
3) git submodule update --recursive

Then you can open and build the project using Qt Creator. Then it should compile it.

2024-03-18 14:27 UTC, SebastianViollaz commented
I find this:

Here an overview of the mission:
![image](https://github.com/mavlink/qgroundcontrol/assets/85691148/fe9cf974-9b9c-45f2-b930-4e83e28c2774)

**Null value in item** 
![image](https://github.com/mavlink/qgroundcontrol/assets/85691148/51cb2e17-5438-468e-95cf-73bd43cd9626)
I see a null value in the Take Off item

![image](https://github.com/mavlink/qgroundcontrol/assets/85691148/4edb2036-8e37-4d78-a994-53bcd076a7f6)

It seems like the "L" is showed too but a null value too.

**No map loaded**
As you can see in the previews photos the map isn't load properly. IN the 2D view is OK but no in 3D.
I change the source from Bing to Google and the problem solved. I don known if the problem is the source or what because in the 2D view is properly showed.
![image](https://github.com/mavlink/qgroundcontrol/assets/85691148/fc4110d2-382c-4d25-b6e2-3f93f2bc72bb)


**ROI not showed**
As you can see in this image the ROI is no longer visible in the 3D view. 
![image](https://github.com/mavlink/qgroundcontrol/assets/85691148/169eb71e-9611-42d8-84cb-ac0f4850be0d)
![image](https://github.com/mavlink/qgroundcontrol/assets/85691148/7d30002d-fa89-4c76-be02-e85761a5dee6)



This is the flight plan that i'm using so you can test it
[LaVerbena_V2.zip](https://github.com/mavlink/qgroundcontrol/files/14637661/LaVerbena_V2.zip)

2024-03-18 14:59 UTC, omid-esrafilian commented
@SebastianViollaz 
Thanks much for the feedback.
Can you please also share with me the osm file you use, then I can test the whole scenarios and find out what is the problem.

2024-03-18 15:01 UTC, SebastianViollaz commented
[LaVervena.zip](https://github.com/mavlink/qgroundcontrol/files/14638176/LaVervena.zip)
This is the OSM file

2024-03-18 15:10 UTC, omid-esrafilian commented
@SebastianViollaz 
And which flight control do you use?

2024-03-18 15:14 UTC, SebastianViollaz commented
Im testing with the SITL Ardupilot sim (master version) [https://github.com/ArduPilot/ardupilot](url). (Arducopter)
I'm in linux 22.04LTS (That could be the problem)
I have a non sim Arducopter, i let you known any news when i test it with this feature.

2024-03-18 17:13 UTC, SebastianViollaz commented
I think that in the mission that  i provied i don use the ROI that is in the tool side bar in the plan editor. 
I add a mission item that change it command to the ROI (That because with the ROI that is in the tools bar an error is given). THis error was recently fixed in the master version #11159 if you marge maybe you can solve the problem of the ROI not showed

2024-03-18 18:40 UTC, omid-esrafilian commented
@SebastianViollaz 
Thanks for the information.
I have tested the code with PX4 flight control. But, in order to display the mission in 3D View, I use the MAVLINK command type to differentiate each item in the mission. I assumed that the items in the mission were independent of the flight control system being used. However, it seems that they are not. Therefore, please let me test the code with Ardupilot to confirm this.

2024-03-19 14:10 UTC, omid-esrafilian commented
@SebastianViollaz 
The problem was that Ardupilot uses "MAV_CMD_DO_SET_ROI" to set the ROI which is Deprecated. 
I have also included the latest changes from the upstream master branch. 
Additionally, you should be able to use Bing as the map provider now.
Can you please test the code and see if the issues are solved?

2024-03-19 14:28 UTC, SebastianViollaz commented
Tested, properly working for me

2024-03-19 14:34 UTC, omid-esrafilian commented
@SebastianViollaz 
Perfect. Thanks much for the feedback.

2024-04-16 18:55 UTC, DonLakeFlyer requested changes

2024-04-16 21:11 UTC, omid-esrafilian commented on src/ui/preferences/FlyViewSettings.qml
> +                        var filename = qsTr(_viewer3DOsmFilePath.rawValue);
@DonLakeFlyer 
Thanks for your comment. I just fixed that.

2024-04-17 17:01 UTC, DonLakeFlyer commented
@HTRamsey Can you look at the docs failure? I Quick Look by me seems to indicate that the check for a push has been removed and things which should be push only are running on pulls.

2024-04-19 15:12 UTC, omid-esrafilian commented
@DonLakeFlyer 
The CI builds seem to work without error now, after rebasing with upstream/master.

2024-04-19 15:31 UTC, merged