[DONT MERGE] Stable v4.4 vs Stable v4.3
mavlink/qgroundcontrol pull request #11276
Opened 2024-03-28 02:57 UTC by julianoes

This is just the diff of the `Stable v4.4` branch with backports on top of the `Stable v4.3` branch.

It's basically an effort to get a v4.4 out before we go to v5 which includes major refactoring and Qt6.

Things that conflict and didn't make it in, are:

- Qt6
- cmake stuff
- CI changes
- Any rework/refactoring on top of Qt6
- 3D maps (https://github.com/mavlink/qgroundcontrol/pull/10948, and [follow up PRs](https://github.com/mavlink/qgroundcontrol/pulls?q=is%3Apr+is%3Aclosed+merged%3A%3E2023-11-30+3d))
- Airlink (https://github.com/mavlink/qgroundcontrol/pull/10940)

Below is the full list that I went through, formatted to avoid backlinks everywhere.

The full list is taken from:
https://github.com/mavlink/qgroundcontrol/pulls?page=9&q=is%3Apr+is%3Aclosed+merged%3A%3E2023-11-30

```
## Page 9

✅ DONE https://github.com/mavlink/qgroundcontrol/pull/9896
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/10331
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/10485
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/10605
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/10875
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10882 -> docs migration?

❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10884 -> Qt6
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10886 -> Qt6
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10888 -> Qt6

❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10893 -> docs tests
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10894 -> docs tests
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/10895 -> fixed conflict from 4.3 to 4.4

✅ DONE https://github.com/mavlink/qgroundcontrol/pull/10889

## Page 8

❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10901 -> already in 4.3 branch

✅ DONE https://github.com/mavlink/qgroundcontrol/pull/10902
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/10903
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/10904
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/10905
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/10906
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/10907
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/10908

❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10909 -> UI rework
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/10910
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10911 -> cmake
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10912 -> Qt6
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10915 -> Qt6

✅ DONE https://github.com/mavlink/qgroundcontrol/pull/10916
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10919 -> conflicts

✅ DONE https://github.com/mavlink/qgroundcontrol/pull/10921
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10925 -> probably conflicts
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10926 -> Qt6
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10927 -> Qt6
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10928 -> Qt6
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10929 -> Qt6
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10930 -> Qt6
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10931 -> Qt6
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10932 -> Qt6
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10933 -> Qt6

## Page 7

❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10934 -> Qt6
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10935 -> Qt6
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10936 -> Qt6
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10937 -> Qt6
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10939 -> Qt6
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10939 -> Qt6
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10940 -> conflicts a lot
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10942 -> cmake
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10944 -> Qt6
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10946 -> Qt6
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/10947 (miracle)
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10948 -> conflicts a lot
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10954 -> CI
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10958 -> CI
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10960 -> Qt6
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/10961
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10963 -> Qt6
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/10964 (miracle)
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/10965
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/10966
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10967 -> conflicts
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/10969
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/10970 (miracle)
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/10971
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/10972
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10976 -> major rework

## Page 6

✅ DONE https://github.com/mavlink/qgroundcontrol/pull/10978
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/10981
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10983 -> conflicts
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10984 -> major rework
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10989 -> major rework
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10991 -> major rework
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10993 -> major rework
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/10996 -> major rework
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/11001 -> conflicts
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/11002 -> major rework
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/11003 -> major rework
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/11005 -> conflicts
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/11006 -> major rework
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/11009 -> cmake
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/11012 -> cmake
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/11014 -> Qt6
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/11016 -> Qt6
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/11019 -> Qt6
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/11025
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/11027
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/11028
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/11032
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/11034 -> major rework
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/11035 -> Qt6, major rework
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/11038 -> Qt6, major rework

## Page 5

❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/11040 -> rework
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/11042 -> rework
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/11044 -> rework
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/11045 -> Qt6
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/11046 -> rework
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/11047 -> conflicts
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/11048 -> 3D not merged
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/11051 -> conflicts
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/11052 -> rework
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/11053
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/11054
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/11055 -> rework
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/11057 -> rework
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/11058 -> 3D not merged
✅ DONE https://github.com/mavlink/qgroundcontrol/pull/11059
❌ SKIP https://github.com/mavlink/qgroundcontrol/pull/ [...]

2024-03-30 18:48 UTC, DonLakeFlyer commented
Not sure it's such a great idea to back port everything that can be back ported over as opposed to a piecemeal approach for only the most important stuff that would need to come over. The reason being is that this version won't see the light of day as a daily which gets extended use before moving to stable. It could likely be pretty flaky without knowing.

2024-04-01 04:25 UTC, julianoes commented
@DonLakeFlyer I agree. However, it's hard to draw the line. If we include some features like gimbal control (which is why we're doing this), then we ought to include other features as well that are well contained.

I assume you understand that we're in a bit of a tricky situation trying to release something until all the big/great refactoring (and Qt6) is done and working for each and every config. I assume it's ok to drop v4.4 if v5 can be released within a few weeks but we probably don't want to wait for too long either.

2024-04-03 11:55 UTC, Davidsastresas commented
I understand both your points, but I think we are in a particular situation regarding master right now. I am not sure if it is the status right now, but for some time it has been broken, with this process of porting to qt 6, etc. At least in my close contacts, the very few people/companies that used to use always master instead of stable, stopped doing so momentarily because of this instability in master lately. So I think this is important to consider it in the argument of some features going to stable before spending enough time in daily first.

On a different note, I recently checked the above commits when rebasing the gimbal PR to 4.4, and I think the  highest risk feature of getting through with little testing is probably video tracking, and I don't think it is high risk anyway. The rest of the commits are mainly bug fixes, some of them very important, like that crash fixed in 19462a3, so from my point of view I think it isn't too crazy to include all of this in the next 4.4 release.

But of course, if we have a defined timeline for master and it is reasonable, I am okay too with cherry-picking just less stuff, as I see Don's point of the added overhead on including this now.

By the way Don, if you could take a quick look at https://github.com/mavlink/qgroundcontrol/pull/11264 to be sure you are fine with it, I fixed all the stuff you suggested in the initial draft PR. I was holding on considering it good until you give the ok. Thank you very much!

2024-04-04 01:30 UTC, rmackay9 commented
Slightly tangential and at the risk of overextending myself I have been thinking for a few months that I should perhaps assist somehow with the release management of QGC.  Perhaps I could assist with the issue analysis and tracking like I do for AP Copter and Rover.

2024-04-04 18:14 UTC, HTRamsey commented
Now that I'm done with the gstreamer fixes, the cmake stuff is mostly usable for test builds. There are a few more things that would need to be done before a release, but nothing too significant. I had a lot of feature improvements and other stuff I was working on but I can help run through a bunch of fixes first if that would help. I believe many of the issues are due to changes in QML widget properties/signals in Qt6. It's not really my place to comment as just some guy, but we could resolve as many issues as possible for a release and then switch over to CMake afterwards.

2024-04-04 21:17 UTC, julianoes commented
Thanks for the offer @rmackay9, I think any help in that direction would be very valuable!

@HTRamsey so you're saying we should/could just go straight to v5 based on Qt6 instead? Last time I checked it was missing a few things, and I wasn't sold on all UI changes. That's probably a broader discussion and I need to do some testing before that.
To me it feels like it's still many weeks off but I might be wrong on that.

2024-04-05 14:27 UTC, DonLakeFlyer commented
> Slightly tangential and at the risk of overextending myself I have been thinking for a few months that I should perhaps assist somehow with the release management of QGC. Perhaps I could assist with the issue analysis and tracking like I do for AP Copter and Rover.

That would be incredible. I have limited hours in a day to work on QGC. If a set of folks could help with issues and then just assign them to me (after they are determined to be real enough and have good details) I can spend my time fixing problems. I can tend to fix things very quickly.

Regarding the current state of master: If folks are finding it unstable for general use that should be an easily fixed problem. The majority of changed are UI in nature which tend to take little effort to fix once known. The key is "once known". I took a quick look through new Issues. Other than some some video stuff I'm not seeing much reporting on a pile of problems with master. So that would seem to indicate to me that people are trying daily but not helping out with reporting the problem they find. If people that have contacts can ask them to get back to using daily again on a normal basis and report the problems I will get it fixed up ASAP. It should not take very long at all.

As far as creating a new Stable release can someone explain the driving force between needing this? I see a few things:
* Created a new Stable from a bunch of cherry-picked stuff from master isn't really a new "Stable". It's just a cherry-picked Daily build which will require ongoing maintenance to fix since it has had zero bake time. The other problem is that Qt6 changes in Qml are pervasive, hence any new Qml you pull into some other build which doesn't use Qt6 may be problematic. There is no way to tell when these sorts of changes can fail without running QGC and hitting the specific part of the ui. I'm not super interested in having to fix all of this up by piecemeal putting things back to Qt5. I would much rather move forward.
* Daily doesn't work well now and people want to try some of the new stuff. That should be fixed by improving Daily quality, not be creating a new Stable.
* There seems to be a lot of interest in the new gimbal stuff. That hasn't even been merged in yet! I don't see how you make a new Stable with that in it when nobody has ever even had a chance the try it yet. Things should be given bake time in Daily to wring them out both from a UX perspective and from a functionality perspective. Again, I come back to why this needs to be rushed into a "Stable" instead of a Daily.

So for me the question remains, why do we need a new Stable so quickly after the last Stable was released? We have never done that before. Why can't we follow a regular, longer release cycle.

2024-04-06 00:45 UTC, rmackay9 commented
I'm very interested in getting the new gimbal stuff out to the community because it's a great leap forward in terms of usability for one of the major use cases of drones.  I also see tons of manufacturers hacking up their own versions of MP and QGC which is a clear sign that this should be in the main version.

I actually agree that there hasn't been much bake time for the gimbal stuff so I think it makes a lot of sense to go into Daily, go through some beta testing, there will undoubtedly be some fixes and then finally release it as stable.

.. but let's get that darn gimbal PR merged asap!

If I were to run a QGC gimbal beta on the AP forums would that be OK?  that's where I'm comfortable, have the necessary logins, and it would also allow me to weed out the AP specific issues from the actual QGC issues.  I'd also likely get backup from other devs and pro users.

2024-04-06 14:44 UTC, DonLakeFlyer commented
> If I were to run a QGC gimbal beta on the AP forums would that be OK?

That would certainly make me feel more comfortable. 

That said, there are two options here:
1) Only include pull https://github.com/mavlink/qgroundcontrol/pull/11264 into a new stable. This would only require targeted testing/feedback on the gimbal stuff
2) Include this pull here which is much more comprehensive with across the board changes as well as the gimbal pull. This would require more end to end QGC testing to verify

The approach for either would be to work from Stable_V4.3 as the base as opposed a true daily build. Folks can install from the CI artifacts for testing. If @rmackay9 is committed to running a beta on this to wring out it. And if @julianoes and @Davidsastresas are committed to responding to issues and fixing problems found in the beta. Then I'm fine with taking approach 2 which is a more comprehensive set of fixes prior to a major 5.0 release.

2024-04-06 18:15 UTC, julianoes commented
The way I see "Stable 4.4" is that it is most bugfixes that have been merged since 4.3 as well as some features, such as gimbal, which is lower risk to me as it is a new feature on top of the existing base, rather than "everything new, better and different" that I see in master. My fear is that it will take a long time until we can get a release out with master but I might be wrong with that.

So, given that, the reasonable thing to do, is probably try out master and collect the issues that I see, and make a more informed decision after that.

2024-04-06 18:49 UTC, DonLakeFlyer commented
It's absolutely going to be a while before a new stable comes out on master. I'm going through a huge UI rework which is going to take a while to finish and settle out. So my suggestion is if folks are happy with signing up for the work is to create a new stable from this pull and the gimbal pull and then wring it out with a beta test group and call it 4.4

2024-04-07 15:50 UTC, DonLakeFlyer commented
Ok, so it looks like @julianoes is ok with the path I proposed. Waiting to hear back from @Davidsastresas if he's ok with it as well. After that we can pull the trigger on merging into Stable_4.3 for a new 4.4 release.

2024-04-07 23:47 UTC, Davidsastresas commented
Sorry but I got a bit lost on the last 3 messages @DonLakeFlyer. I think you meant if I am okay with doing this over 4.3, dealing with it as a beta and delivering executables in that forum thread managed by @rmackay9 , correct? If so, I am okay with it, and I will be responsive in the following weeks if any problem arises regarding that.

Also, just to be sure we are on the same page, you meant also to do the equivalent gimbal PR for master now? or you were implying to give it a bit of time in that beta testing group before preparing a gimbal PR for master?

Thanks.

2024-04-08 00:22 UTC, rmackay9 commented
Don's plan sounds OK to me.

Re running the release, I'm happy to fit in with however you guys normally run do it but my current thought is to do something like this:

- run the AP side of the QGC-4.4 beta from [AP's discuss server's QGroundControl category](https://discuss.ardupilot.org/c/ground-control-software/qgroundcontrol/71)
- start with a beta announcement in the above forum and on facebook
- create a new consolidated issue in the [QGC issues list](https://github.com/mavlink/qgroundcontrol/issues) including a link back to the initial report topic and the status of the issue (e.g. requires analysis, confirmed bug, enhancement request, resolved)
- with each reported issue I'll try to reproduce it if I can and hopefully Don (and perhaps others) can help me clarify what we plan to do with each (e.g. fix it, raise an issue and let it go as a "known issue", etc).
- every week or two we release a new beta version with an accompanying beta release announcement.. repeat until we're happy that it's safe and then do the stable release

2024-04-08 15:02 UTC, DonLakeFlyer requested changes

2024-04-08 15:05 UTC, DonLakeFlyer commented
Ok, so I've reviewed this pull. It's not a huge set of changes but it's also not a minor change. My suggest to wring this out would be to run a beta on the PX4 side with some folks to do some overall testing on QGC (as opposed to gimbal focused). I also think the person who did the camera tracking stuff should be brought in to retest since that is a major feature which is coming over from master. @julianoes Do you think you could run a beta on the PX4 side for this?

2024-04-10 16:14 UTC, DonLakeFlyer commented
Not sure what happened here. Seems like my review comments are gone now and the whole chain of discussion that was here is gone as well. Is that the case for everyone or just me?

2024-04-10 17:10 UTC, DonLakeFlyer commented
Duh!

Anyway, so the Gimbal stuff is in now. So next steps is fix this up to my review comments and merge this in as well. Then we will be ready to announce a beta.

2024-04-11 00:11 UTC, julianoes commented
@DonLakeFlyer yes, I'll try to have PX4 people try it out as well. Is there a link, like a pre-release github tag where it can be downloaded from?

Regarding your review commits, thanks! I need to find out which PR/commits introduced them and drop them.

2024-04-11 00:21 UTC, julianoes commented on src/AutoPilotPlugins/APM/APMSensorsComponentController.cc
> +                              Q_ARG(QString, varText));
Dropped the commit.

2024-04-11 00:21 UTC, julianoes commented on src/AutoPilotPlugins/PX4/SensorsComponentController.cc
> +                              Q_ARG(QString, varText));
Dropped the commit.

2024-04-11 00:23 UTC, julianoes commented on src/QGCApplication.cc
> +      QMetaObject::invokeMethod(_rootQmlObject(), "showVehicleSetupTool", Q_ARG(QVariant, arg));
Dropped the commit.

2024-04-11 00:25 UTC, julianoes commented
@DonLakeFlyer I saw 3 comments by you and dropped the two commits, then force pushed. Alternatively, you can also review which commits went in via the commit list.

2024-04-11 00:46 UTC, DonLakeFlyer commented
> Is there a link, like a pre-release github tag where it can be downloaded from?

No. Folks will need to install from GitHub CI artifacts. You could also copy those links and put them in a forum post.

2024-04-11 13:45 UTC, hendjoshsr71 commented
I'm trying to test the gimbal joystick support, but the button doesn't appear in the CI artifact linux app image. 

Anyone know why?

![image](https://github.com/mavlink/qgroundcontrol/assets/69225461/8d281daf-5749-4a25-8837-4bcf9c37fb67)

2024-04-11 17:40 UTC, DonLakeFlyer commented
> I'm trying to test the gimbal joystick support, but the button doesn't appear in the CI artifact linux app image.

That would be a @Davidsastresas question

2024-04-11 22:30 UTC, Davidsastresas commented
@hendjoshsr71, On this PR, only support for joystick buttons was added. In the buttons submenu you can select actions to move up/down/left/right and also some actions like center, etc.

2024-04-12 03:40 UTC, hendjoshsr71 commented
> @hendjoshsr71, On this PR, only support for joystick buttons was added. In the buttons submenu you can select actions to move up/down/left/right and also some actions like center, etc.

Alright. 
That option is on the wiki but I had a feeling it it was only available via a PR.

I tried the other main gimbal PR but the build artifact failed to load on Linux.

2024-04-12 08:03 UTC, julianoes commented
@hendjoshsr71 

> I tried the other main gimbal PR but the build artifact failed to load on Linux.

What was the error?

2024-04-12 15:31 UTC, Davidsastresas commented
@hendjoshsr71 , please let us know the error you found opening the .appImage. About the executables of this PR, they are here:

https://github.com/mavlink/qgroundcontrol/actions/runs/8641829187
https://github.com/mavlink/qgroundcontrol/actions/runs/8641829183
https://github.com/mavlink/qgroundcontrol/actions/runs/8641829180
https://github.com/mavlink/qgroundcontrol/actions/runs/8641829174

2024-04-12 23:14 UTC, rmackay9 commented
Of course its totally cool that @hendjoshsr71 is helping with alpha testing, we are also going to do beta testing with the community as soon as this PR goes in.  I guess I'm just questioning if the issues raised by Josh need to hold up the start beta testing?

I think we will uncover issues and enhancement requests during beta testing and we will need to manage those and decide which are really critical to address before a stable release.

2024-04-13 08:00 UTC, julianoes commented
@DonLakeFlyer is there a reason we can't do a pre-release via GitHub? And have the artifacts there?

2024-04-13 15:32 UTC, DonLakeFlyer commented
> is there a reason we can't do a pre-release via GitHub? And have the artifacts there?

Other than I don't really know how that works, I don't think so. Do you do that manually?

2024-04-15 17:57 UTC, DonLakeFlyer commented
@julianoes So what the current state of getting this in?

2024-04-15 18:28 UTC, julianoes commented
Sorry, I was busy for a bit. Looking into it today.

I see there is a GitHub action that uploads to s3 on tag. I didn't see the one that uploads to the release page, like here: https://github.com/mavlink/qgroundcontrol/releases/tag/v4.3.0

Maybe that's manually done by downloading from s3 and then uploading there?

2024-04-15 18:30 UTC, DonLakeFlyer commented
The releases which are GitHub releases aren't automated. @mrpollo Had been making those by hand.

2024-04-15 21:38 UTC, julianoes commented
Ok, we can automate that in the future. 

For now we'll have to make sure a no s3 upload happens for the RC version using some sort of tag wildcard here:
https://github.com/mavlink/qgroundcontrol/blob/master/.github/actions/upload/action.yml#L36

2024-04-15 21:54 UTC, julianoes commented
@DonLakeFlyer ah you're right. So in that case we can create an RC tag here, right?

2024-04-16 18:32 UTC, DonLakeFlyer commented
Do you need to set a tag to manually create a release in GitHub. Settings a tag will kick off the regular release process so you don't want to do that.

2024-04-18 01:30 UTC, julianoes commented
@DonLakeFlyer I think the area around the arm button might be a bit too big...

![Uploading 2024-04-18_13-29.png…]()

2024-04-18 15:15 UTC, DonLakeFlyer commented
@julianoes Can you upload the image again?

2024-04-18 19:26 UTC, julianoes commented
Sorry, that clearly didn't work. I can later. For me it's too big when I click on the top left to arm.

2024-04-19 02:03 UTC, julianoes commented
Here it is, again:

![2024-04-18_13-29](https://github.com/mavlink/qgroundcontrol/assets/1419688/a29b6f7e-d17d-4048-b858-0bfcf7c1fdb4)

2024-04-19 15:38 UTC, DonLakeFlyer commented
I"m just realizing that I'm confused at to what this pull is showing. Isn't Stable_V4.4 a brand new branch which only has the new gimbal stuff it? Did you already merge all the other master stuff into Stable_V4.4?

2024-04-19 15:39 UTC, DonLakeFlyer commented
For the Arm thing what are you testing against? It's not showing any Sensor Status in the dropdown?

2024-04-20 11:21 UTC, Davidsastresas commented
> I"m just realizing that I'm confused at to what this pull is showing. Isn't Stable_V4.4 a brand new branch which only has the new gimbal stuff it? Did you already merge all the other master stuff into Stable_V4.4?

I rebased the gimbal commits on the current Stable_V4.4, and Stable_V4.4 is the PR of this current thread.

About the issue with the arm panel @julianoes indicated, I don't recall seeing that odd behaviour on Ardupilot.

2024-04-20 22:58 UTC, julianoes commented
@DonLakeFlyer 

> I"m just realizing that I'm confused at to what this pull is showing. Isn't Stable_V4.4 a brand new branch which only has the new gimbal stuff it? Did you already merge all the other master stuff into Stable_V4.4?


No, if you read through my pull request description it says that I tried to include all bugfixes and improvements which were not part of the bigger rework and Qt6. I then list all the PRs that are part of this branch. And you can also see that if you list the commits. Does that make it clearer? I'm happy to change it if you disagree with this approach.

2024-04-21 22:22 UTC, julianoes commented
Nevermind about the big window to arm. I see this with QGC 4.3.0 as well. Must be something about my setup. Something to debug another day.

2024-04-22 04:07 UTC, julianoes commented
However, I broke the planning view:
```
qrc:/qml/MainRootWindow.qml:130: ReferenceError: viewSwitch is not defined
```

2024-04-23 01:09 UTC, julianoes commented
It looks like the commits that broke the plan view switching was part of: https://github.com/mavlink/qgroundcontrol/pull/10875/commits/b65dab72d5eaf7687aa101ed8a6fe505ea97d46b

I've reverted the commit and pushed again.

2024-04-23 01:24 UTC, julianoes commented
![image](https://github.com/mavlink/qgroundcontrol/assets/1419688/ce3203d5-68ad-4504-a612-332fae479aa4)

@DonLakeFlyer and @Davidsastresas it looks like no release without tag. So, I think, we either have to release v4.4.0 and add a fixup release v4.4.1 a week or two later, or we have to add wildcards to all the upload actions to prevent uploads for tags like `v4.4.0rc1`.

I'd just release it but it's up to you.

2024-04-23 19:56 UTC, julianoes commented
Ok, I'll try to do exactly that then. I assume I only need to prevent the s3 upload in this branch and not master.

> As far as my confusion on this pull. Is the idea to not merge this ever and just leave the Stable 4.4 branch this pull refers to as the 4.4 moving forward. If so, then I understand and this makes sense.

Exactly. The pull is just to show the diff and have a place for the discussion.

2024-04-23 21:29 UTC, DonLakeFlyer commented
> I assume I only need to prevent the s3 upload in this branch and not master.

Right. Just hack the CI workflows on Stable_V4.4.

2024-04-23 21:31 UTC, DonLakeFlyer commented
> Also, I probably need to fix the Android build.

That looks like the "Remove the additional SDK" problems: https://github.com/DonLakeFlyer/UAV-RT-TagTracker/blob/master/.github/workflows/Herelink_Android.yml#L56

2024-04-23 22:15 UTC, HTRamsey commented
You could do that, or I believe the 'proper' fix is to use split("-") or tokenize("-") to remove the ext

2024-04-24 05:24 UTC, julianoes commented
Feel free to push commits to this branch to fix.

2024-04-24 08:47 UTC, Davidsastresas commented
I pushed 2 commits, to fix android build and remove the "upload to S3" step.

So from here, we create a release manually here in github, and then revert the "don't upload to s3" commit, and we should be where we were talking about right?

2024-04-24 08:55 UTC, julianoes commented
Thanks @Davidsastresas!

2024-04-24 15:59 UTC, DonLakeFlyer commented
> and then revert the "don't upload to s3" commit

I'd just leave that in until you do the final release.

2024-04-25 02:33 UTC, julianoes commented
https://github.com/mavlink/qgroundcontrol/releases/tag/v4.4.0rc1

2024-04-30 07:43 UTC, rmackay9 commented
@DonLakeFlyer @julianoes,

Can I use the artifacts that Julian has linked above to start the beta testing or should I wait until this PR has been merged to start?

2024-04-30 18:36 UTC, DonLakeFlyer commented
That would be a @julianoes question. I'm only advising on the various ways to do this with the current CI system. I'm not in the middle of the dev for it.

2024-04-30 21:26 UTC, julianoes commented
Yes @rmackay9 use the binaries from the [RC1 release](https://github.com/mavlink/qgroundcontrol/releases/tag/v4.4.0rc1).

The PR doesn't get merged. It just shows the diff to v4.3.0. The release will be made from this release branch.

2024-05-01 19:15 UTC, HTRamsey commented
Should we add the newer gstreamer qt5 plugin? It doesn't require code changes on our side and likely performs much better.

2024-05-02 01:24 UTC, julianoes commented
@HTRamsey you're call, sure!

2024-05-02 11:10 UTC, rmackay9 commented
I'm a little late in starting the beta with the AP community because it's "Goldenweek" here in Japan.  I plan to start early next week.

2024-05-02 15:15 UTC, DonLakeFlyer commented
> Should we add the newer gstreamer qt5 plugin? It doesn't require code changes on our side and likely performs much better.

My opinion would be less is more. Given the fact that this whole release will have way less testing time done on it. I wouldn't change things in video which always gives us trouble.

2024-05-06 23:11 UTC, HTRamsey commented
Just FYI we need to update android gstreamer to 1.18.6 because they've taken down every release that isn't the last revision for each major version.

2024-05-15 10:47 UTC, rmackay9 commented
Hi, Sorry for taking so long to start the beta testing.  It it my top priority now but as I went to start the beta I realised that I'd better test it myself and provide instructions on how beta testers can install it and this is where I've run into troubles.  I'm struggling a bit to get either QGC installed on my Herelink or get the Herelink video forwarding to my PC where I can run the beta version.

Anyway, I'm consulting with Michael Oborne, HenryW, DavidS and others so surely I'll get it working soon.

2024-05-20 06:29 UTC, rmackay9 commented
Hi, when I tell users to install the beta using the "Artefacts" I see that the [Checks page](https://github.com/mavlink/qgroundcontrol/pull/11276/checks) has multiple installers for each platform.  So for example, for Windows users, should I be telling them to install using the 1st one or the last one?
![image](https://github.com/mavlink/qgroundcontrol/assets/1498098/6bbe4c16-32a5-4f58-807a-950dfd4680d9)

2024-05-20 06:41 UTC, HTRamsey commented
The On Pull Request one is before getting Rebased onto the branch, the On Push is after. So the On Push one is the correct one.

2024-05-20 07:30 UTC, rmackay9 commented
@HTRamsey, thank you very much!

I've finally started the beta testing with [this announcement on the AP forums here](https://discuss.ardupilot.org/t/qgc-4-4-available-for-beta-testing/118091).  I've also [created this issue for tracking](https://github.com/mavlink/qgroundcontrol/issues/11559).

Of course I'm very happy if PX4 users want to get involved as well but that should be managed by someone who knows PX4 on the PX4 forums because I couldn't possibly triage issues they might raise.  I suspect we don't need to double up on beta testing though for this small-ish release.  When it comes to the next major release we probably will.

2024-05-20 09:22 UTC, Davidsastresas commented
I pushed 2 commits. A few days ago @andrefreitas97 reported sometimes the gimbal widget wasn't appearing. He related that to the amount of retries we were doing for the message requests to Ardupilot. It was kind of related:
- Sometimes during parameter download traffic was too high and the requests from QGC to Autopilot got lost, so the handshake wasn't working. Now we wait for params download to perform the handshake.
- We were sending several requests for those messages, but we were not waiting any time between them, and this was messing too with the handshake. Now we wait 1 second between each request done for gimbal_manager_status message.

2024-05-20 09:26 UTC, Davidsastresas commented
By the way @rmackay9, @julianoes prepared a nice release page for users to not need to mess up with build artifacts. Everything should be tidy and nice there:
https://github.com/mavlink/qgroundcontrol/releases/tag/v4.4.0rc1

2024-05-20 10:08 UTC, rmackay9 commented
@Davidsastresas, Great, thanks for that.  I've updated [the release announcement](https://discuss.ardupilot.org/t/qgc-4-4-available-for-beta-testing/118091) links to point to Julian's release page.

2024-05-20 13:45 UTC, Davidsastresas commented
I pushed a couple of commits to fix CI, and I pushed a new pre-release with the fixes mentioned earlier about gimbal handshake. It should be here:

https://github.com/mavlink/qgroundcontrol/releases/tag/v4.4.0rc2

2024-05-21 01:27 UTC, rmackay9 commented
I've updated the [beta release announcement](https://discuss.ardupilot.org/t/qgc-4-4-available-for-beta-testing/118091) to port to @Davidsastresas's [-rc2 page](https://github.com/mavlink/qgroundcontrol/releases/tag/v4.4.0rc2).

2024-05-21 04:18 UTC, rmackay9 commented
Is there a weekly meeting or chat where we can discuss [the issues that are coming up](https://github.com/mavlink/qgroundcontrol/issues/11559)?  I guess we could do all the communication in this PR as we are now if people prefer.  There are 4 issues at the moment (all from me so far :-))

2024-05-21 14:10 UTC, mrpollo commented
Thanks for the announcement post @rmackay9 I'll help share as well

Regarding the whole artifacts thing, we should have a bot that pulls the artifacts and posts a comment with links to download, Ill try to set it up this week.

2024-05-22 04:13 UTC, julianoes commented
> Regarding the whole artifacts thing, we should have a bot that pulls the artifacts and posts a comment with links to download, Ill try to set it up this week.

@mrpollo there is the GitHub action https://github.com/svenstaro/upload-release-action which does it.

Also see: https://github.com/mavlink/MAVSDK/blob/7d6356d5147da8686e58ce041b79dc2457a47f5b/.github/workflows/main.yml#L258-L260

2024-05-22 04:15 UTC, mrpollo commented
Thanks @julianoes 

Testing out things here https://github.com/mavlink/qgroundcontrol/pull/11561

2024-05-22 04:32 UTC, julianoes commented
@mrpollo I don't think we need it added to this PR. We just need it to be added the release for each release candidate tag.

2024-05-22 04:33 UTC, julianoes commented
Who knows how to deal with Android CI?

```
     /home/runner/work/_temp/shadow_build_dir/android-build/build/intermediates/merged_manifests/release/AndroidManifest.xml:2: AAPT: error: invalid android:versionCode '664400rc2000'.
```

2024-05-22 04:48 UTC, Davidsastresas commented
> Who knows how to deal with Android CI?
> 
> ```
>      /home/runner/work/_temp/shadow_build_dir/android-build/build/intermediates/merged_manifests/release/AndroidManifest.xml:2: AAPT: error: invalid android:versionCode '664400rc2000'.
> ```

That is expected. Android takes the tag to compute the android version, and it needs clean major.minor.patch.dev naming. So, if the tag would be 4.4.0.2 Android CI would build. However, that means it will get built as Stable and not as Daily.

2024-05-22 05:04 UTC, julianoes commented
Oh, right @rmackay9. So we can ignore it, and then make another RC when required. RCs should be Stable, I'd say.

2024-05-22 07:38 UTC, rmackay9 commented
The Herelink .apk is available now as well, thanks @julianoes!
https://github.com/CubePilot/qgroundcontrol-herelink/releases/tag/v4.4.0.3

I've also found [this random YouTube video](https://www.youtube.com/watch?v=a-cLzYD7HBk) that gives pretty good instructions on how to install it.

2024-05-30 06:44 UTC, julianoes commented
Here is a warning to fix:
```
qrc:/qml/QGroundControl/FlightMap/VehicleMapItem.qml:48: TypeError: Cannot read property 'gimbalController' of null
```

2024-05-31 02:20 UTC, rmackay9 commented
From a quick test this latest change fixes the recording button!
![image](https://github.com/mavlink/qgroundcontrol/assets/1498098/02eb43a8-e1d8-46eb-a9d8-aeaaf2904f7a)

2024-06-03 05:19 UTC, HTRamsey commented
You may want to consider including #11269 since that is kinda relevant to all of the camera work

2024-06-03 07:42 UTC, julianoes commented
Done, thanks @HTRamsey.

2024-06-03 09:15 UTC, Davidsastresas commented
Everything looks very nice, thank you everybody. 

I just pushed a couple of commits fixing the qml warning Julian posted a few comments back, and also fixing the offline maps menu, it was broken after some of the commits cherry-picked from master.

2024-06-03 14:03 UTC, rmackay9 commented
Hi, I think maybe we should consider one more -rc (aka -rc4) and leave it out there testing for a few days and if that goes OK then release it as the official version?

The feedback on the [beta testing thread](https://discuss.ardupilot.org/t/qgc-4-4-available-for-beta-testing/118091) has slowed so a new -rc may help get some additional feedback.  We have a few issues on [the issues list](https://github.com/mavlink/qgroundcontrol/issues/11559) but I think they're not critical.  The "Point Home ROI can't be cancelled," might be nice to fix but it's not the end of the world. 

FYI @Davidsastresas @julianoes @DonLakeFlyer?

2024-06-03 15:26 UTC, Davidsastresas commented
Hi Randy.

I checked the matter about cancel ROI for home. It can be done, as it is now, you can click on the label instead of the waypoint:
![Screenshot from 2024-06-03 17-22-26](https://github.com/mavlink/qgroundcontrol/assets/18221398/6d62148c-b21d-40e0-ae5f-c1c4e250d49d)

If clicking the circle icon, it will take it as waypoint and show the "change waypoint to ... " dialog. But if you click the label "ROI Here", it will prompt you with the options to disable ROI.

I think we can do an rc5 with the newer changes and try to get more feedback. Thanks!

2024-06-07 12:05 UTC, rmackay9 commented
I've updated the links to -rc5 on the [AP beta testing thread](https://discuss.ardupilot.org/t/qgc-4-4-available-for-beta-testing/118091).  I'm off on holidays until Wed so ability to test is very limited.

Still, I think we should go ahead and release.  I think we've done a good bit of testing and enough time has passed during the beta period that we can be confident that it is stable and better than 4.3.

Thanks to @julianoes, @Davidsastresas, @DonLakeFlyer and @HTRamsey for their work on this release and also to those who provided feedback during beta testing including:

- HenryW
- cuav_le
- @hendjoshsr71
- @mrpollo

Thanks!

2024-06-11 02:10 UTC, julianoes commented
Closing this pull request as it was just to track the diff but not to be merged.

2024-06-11 02:10 UTC, closed without merging

2024-06-11 02:16 UTC, julianoes commented
Here is the release:
https://github.com/mavlink/qgroundcontrol/releases/tag/v4.4.0

Thanks @rmackay9 for coordinating and communicating the RCs, and @Davidsastresas, and @HTRamsey for the help, and everyone else for the testing and notes.