Gillamkid/value display update
mavlink/qgroundcontrol pull request #11895
Opened 2024-09-18 06:52 UTC by gillamkid

# Description
This PR has 2 commits
1. Fix button sizes in TelemetryValuesBar
    * In QGC 4.4.2 these buttons look fine, but in the master branch they were super squashed looking
2. Organize "Value Display" so it is more scannable
    * Now it is organized with keys on the left and values/inputs on the right, making the form more intuitive and scannable for first time users.
    * The design of the form is now more similar to other parts of QGC, namely the views seen in "Application Settings"

## Sponsor
This contribution was sponsored by [Firestorm](https://www.launchfirestorm.com/)
![654d4f9476ff2a38f37e9ab9_firestorm-homepage-share-img-2](https://github.com/user-attachments/assets/bc1a2c95-b33d-4a2d-af35-4d2d8651d0a2)

## Before

https://github.com/user-attachments/assets/92304f65-fdee-4206-aab8-cc6e3ed7a0cc

## After

https://github.com/user-attachments/assets/52c2dd33-761a-4f0a-8083-f2ba0afa5228

2024-09-18 15:37 UTC, mrpollo commented
Changes look good to me, its a really nice improvement.

@DonLakeFlyer Can you do one last final check here? just want to make sure nothing is lost in the transition

2024-09-18 17:47 UTC, DonLakeFlyer commented
@gillamkid The mp4 seem to be gone now? Maybe just images showing before after changes?

2024-09-18 17:48 UTC, DonLakeFlyer commented
I had taken an initial look at this a bit ago. My concern was with the sizing of the buttons for add/remove columns/row. If they are too small and right next to each other they can be tough to touch with a fat finger on a tablet. I'll need to build it myself and look.

2024-09-18 17:56 UTC, DonLakeFlyer commented
> The mp4 seem to be gone now? Maybe just images showing before after changes?

Don't worry about this. I'm just building it myself to look at it.

2024-09-18 18:25 UTC, DonLakeFlyer commented
Hmm, this is different than I last saw it. I thought there were little button with images for add/remove row/columns. Anyway:

Here is current master. You can see how the buttons are really small. This is because it uses `minTouchPixels / 2` which in reality is incorrect usaget. Since it is smaller than what is touchable on a tablet. It also expose a bug in QGCButton which is not positioning the text correctly.
<img width="458" alt="Screenshot 2024-09-18 at 11 16 34 AM" src="https://github.com/user-attachments/assets/fb70d49c-f5fc-460f-a47a-ca5f5b6bcd23">

Here is what the editable panel looks like with this pull. My opinion is that those buttons end up being way too big and look really strange in this context:
<img width="496" alt="Screenshot 2024-09-18 at 11 11 58 AM" src="https://github.com/user-attachments/assets/25abaa72-dd59-44f9-8d23-887acb499beb">

Here is the same thing but using full minTouchPixels size which is the calculated minimum size of something which is touchable on a tablet. It also shows the text positioning bug in QGCButton which needs fixing. I think this looks way better and is still functional on a tablet from a sizing perspective.
<img width="473" alt="Screenshot 2024-09-18 at 11 10 56 AM" src="https://github.com/user-attachments/assets/8acea4b6-5aff-492e-9c62-fefa58ac4cd7">

2024-09-18 18:49 UTC, DonLakeFlyer commented
> * The design of the form is now more similar to other parts of QGC, namely the views seen in "Application Settings"

Yes, much better to head this direction.

Detailed comments...

Current master which you can see is kind of a mess of complexity and alignment problems:
<img width="242" alt="Screenshot 2024-09-18 at 11 28 18 AM" src="https://github.com/user-attachments/assets/dc7c9f2e-0513-4ea7-adbd-df101045863d">

Here is what this pull looks like. It's better from an alignment perspective. But for me all those divider lines make it look really noisy. Also the Range section needs conversion.
<img width="402" alt="Screenshot 2024-09-18 at 11 33 12 AM" src="https://github.com/user-attachments/assets/bb54ed78-0006-4fde-815d-f5304ab7fe89">

I think you need to take the group layout grouping further than a single group. This is how the new settings stuff works and it ends up looking much better. I also don't think there needs to be toggle visibility. And it groups things more logically. Here is a quick hack on top of your pull to show it heading more in the direction of multiple groupings. Certainly needs more work but I hope you get the idea:
<img width="423" alt="Screenshot 2024-09-18 at 11 46 57 AM" src="https://github.com/user-attachments/assets/a027d53d-fd15-4429-bda3-66b985feb20f">

2024-09-18 18:53 UTC, DonLakeFlyer requested changes

2024-09-18 18:53 UTC, DonLakeFlyer commented on src/QmlControls/QGCRadioButton.qml
> +        leftPadding:        control.indicator.width + (_noText ? 0 : control.leftPadding)
Why this change? This is incorrect in that it doesn't adjust sizing based on the configurable font size.

2024-09-18 18:53 UTC, DonLakeFlyer commented on src/QmlControls/SettingsGroupLayout.qml
> +    property bool   showBorder:         true
I'd leave this as is for now. Don't want to create a new UI paradigm of these group layout without borders until it is really needed. That is already mostly already covered by the SectionHeader control.

2024-09-19 16:02 UTC, DonLakeFlyer commented
If you want I can merge this in and then fix up the rest of the stuff. All simple, take a few minutes for me.

2024-09-19 16:05 UTC, gillamkid commented
> If you want I can merge this in and then fix up the rest of the stuff. All simple, take a few minutes for me. Thanks so much for cleaning this messy stuff up.

Yeah that'd be great! Not sure when I'd get to it

2024-09-20 19:29 UTC, merged