Fixing channel issue with ELRS Mavlink-rc: number of channels is not set by default
mavlink/qgroundcontrol pull request #11969
Opened 2024-10-04 16:22 UTC by msoos

## Description 

If you are using ELRS MAVLINK setup as per: https://www.expresslrs.org/software/mavlink/ then the number of channels will never be set. Hence it will remain 0 -- even though there is clearly control data going through. This is because ELRS is not sending a full RC_CHANNELS packet, only channel update packets, to update the position of the values. Therefore, the number of channels is not set.

This ELRS system forwards BOTH the RC and the Mavlink on the same ELRS link. Using one TX and one RX, you get to have both Mavlink and RC. The Mavlink is forwarded via the backpack chip in the TX to the wifi. You can then connect to this wifi and QGC picks it up automatically, via zero-conf (I think! Very cool) and "just works". Which is great. But the RC doesn't SEEM to work, because the number of channels is never set.

## Test Steps

* Using RX ELRS 3.5.0 (release version, not experimental)
* Using TX ELRS 3.5.0 (release version, not experimental)
* Using TX ELRS Backpack 1.5.0 (release version, not experimental)
* Using SpeedyBee F405 Wing (full, not mini) board, Serial 1 connected to ELRS receiver, set up as per: https://www.expresslrs.org/software/mavlink/

We get connectivity of Mavlink forwarded via ELRS + backpack in the TX via WiFi, however, the radio channels cannot be calibrated, and it cannot arm, because the number of channels is seen as 0. With this fix, calibration works and the craft can be armed.

## How to Reproduce
Connect as per above. Observe that calibration is not possible, the QGC says there is no controller connected.

Checklist:
----------
- [ ] [Review Contribution Guidelines](https://github.com/mavlink/qgroundcontrol/blob/master/.github/CONTRIBUTING.md).
- [x] [Review Code of Conduct](https://github.com/mavlink/qgroundcontrol/blob/master/.github/CODE_OF_CONDUCT.md).
- [x] I have tested my changes.

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-10-11 16:30 UTC, DonLakeFlyer commented
This seems like a bad hack which goes against mavlink spec. Why can't whatever this system is be fixed to respect the mavlink spec?

https://github.com/mavlink/qgroundcontrol/blob/master/src/FirmwarePlugin/PX4/PX4ParameterMetaData.cc#L78. 

RC_CHANNEL.channel_count - Total number of RC channels being received. This can be larger than 18, indicating that more channels are available but not given in this message. This value should be 0 when no RC channels are available.

2024-10-12 11:37 UTC, msoos commented
Thanks for the response @DonLakeFlyer ! It turns out, they send `RC_CHANNELS_OVERRIDE` messages only (not _RAW). Does that change your mind regarding what should be done here?

2024-10-12 18:50 UTC, DonLakeFlyer commented
Hmm, that certainly is a mess. 

I could live with this:
* If RC_CHANNEL.channel_count == 0 then look at the individual chan*_raw values. Count up the number of ones which are not UINT16_MAX. That should be the channel count.
* Comment all this as being a hack to support ELRS (refer to issue below in the comment)
* Create an Issue about all of this with a note to remove it once ELRS is fixed to be correct to mavlink spec

That would work?

2024-11-19 22:01 UTC, DonLakeFlyer commented
Any updates on this?

2024-11-29 10:20 UTC, msoos commented
@DonLakeFlyer Yes, let me do this. Sorry for the delay.

2024-11-29 12:36 UTC, msoos commented
Hi @DonLakeFlyer ,

Can you please check the PR now? It now has your requirements implemented. I checked, it works well. Please merge if you think it's good :)

Thanks,

Mate

2024-12-02 17:45 UTC, DonLakeFlyer requested changes

2024-12-02 17:45 UTC, DonLakeFlyer commented on src/Vehicle/Vehicle.cc
> +        uint8_t num_non_uint16_max = 0;
Can you remove this. It isn't used.

2024-12-04 16:27 UTC, msoos commented on src/Vehicle/Vehicle.cc
> +        uint8_t num_non_uint16_max = 0;
OOps, yes, fixed! Sorry.

2024-12-05 19:11 UTC, DonLakeFlyer commented
All looks good now. Can you squash down to a single commit. Then once the rebuild finishes I'll merge.

2024-12-05 19:54 UTC, msoos commented
Nice, thank you so much! I just squashed :) Let me know how it goes :) Thanks so much,

Mate

2024-12-08 22:55 UTC, merged

2024-12-08 22:55 UTC, DonLakeFlyer commented
@msoos Thanks for fixing this

2024-12-08 22:56 UTC, msoos commented
Thanks so much for merging!