[Draft] Multi Vehicle Panel Overhaul
mavlink/qgroundcontrol pull request #11970
Opened 2024-10-06 12:16 UTC by demirciAhmet

Description
-----------

Related to #11693 

Sorry for the delay, I was busy for a while. Also I tried not to get too involved in the parts that require more complicated changes before the core changes to the new panel design have been completed (guided action confirmation for the panel didn't implemented yet as it requires more comprehensive changes). Here is the current state of the panel overhaul:

- [x] New solid top-right panel implemented, changed overall design of the multi vehicle list. 
- [x] To be able to add *guided action confirmation* to the buttons of the multi-vehicle panel, a new logic *"Select vehicles - Perform action"* implemented (now you first select vehicles from the panel by tapping on them, then perform the action to the selected vehicles, otherwise you had to confirm one by one for the each action, which would be very annoying).
- [ ] Need to implement guided action confirmation for the mv actions
- [ ] I think it will be nice to add a stacked page layout, embedded in the new top-right panel. This way, other components such as the *PhotoVideoControl*, or any other widgets that may be implemented later, can be added to the top-right panel. For now, *"PhotoVideoControl"* anchored to the bottom of the panel as a temporary fix. 

![image](https://github.com/user-attachments/assets/a52249ec-d0ea-4117-8c74-dc848f035845)

Checklist:
----------

- [x] [Review Contribution Guidelines](https://github.com/mavlink/qgroundcontrol/blob/master/.github/CONTRIBUTING.md).
- [x] [Review Code of Conduct](https://github.com/mavlink/qgroundcontrol/blob/master/.github/CODE_OF_CONDUCT.md).
- [ ] I have tested my changes.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-10-11 16:44 UTC, DonLakeFlyer commented
Is there a fixed amount of space you devote to vehicle indicators which scrolling? is this why the list is clipped at the bottom?

2024-10-11 18:18 UTC, demirciAhmet commented
> Is there a fixed amount of space you devote to vehicle indicators which scrolling? is this why the list is clipped at the bottom?

Yes, it has a fixed height (currently half of the panel height), you scroll through the panel if there are many vehicles. This way there is no need to worry about adding new widgets to the panel in the future.

I thought about separating the lower part of the panel for buttons, and other widgets, which will be stacked page by page.

2025-01-13 16:55 UTC, DonLakeFlyer requested changes
So far this is looking really good. Thanks. Biggest problems are real estate problems.

2025-01-14 11:53 UTC, demirciAhmet commented
> When there are no vehicles connected there is an artifact left on the screen in the upper right: <img alt="Screenshot 2025-01-13 at 8 34 54 AM" width="291" src="https://private-user-images.githubusercontent.com/5876851/402620350-fe7ff90b-9832-4eef-af5d-ebbd3bb99bc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY4NTEzMzUsIm5iZiI6MTczNjg1MTAzNSwicGF0aCI6Ii81ODc2ODUxLzQwMjYyMDM1MC1mZTdmZjkwYi05ODMyLTRlZWYtYWY1ZC1lYmJkM2JiOTliYzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTRUMTAzNzE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmNmMmI4ZmY2MjU4YzM3NWNlZmQ2MzgxNzY4ZjA0YWJiNDM0ZjE2YjMxYmQ5MjExYTMyM2IwYTlmOTRmMTE4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.l_T-3J6HucKd_AjqwuSCWgzmGF3pXxSFanrQ6ey8QCc">
> 
> When I am connected to multiple vehicles I see that same artifact and there is nothing that indicates there is a multi-vehicle panel available. If I click on the oval thing the panel finally opens up.

Actually, the idea on that point was that the panel itself, which you can open, close, and use even when connected to a single vehicle, should indicate the availability of a multi-vehicle panel. However, as you mentioned earlier, most users operate QGC with a single vehicle, so this might not be the best design approach.

Perhaps the most suitable option would be to convert the panel into something hidden by default but accessible by swiping from the right side of the screen, similar to sidebar menus on Android. When multiple vehicles are connected, the panel will automatically show itself while still allowing users to open and close it via swiping. What do you think?

2025-01-14 16:46 UTC, DonLakeFlyer commented
Here is what I would do:
* The visibility of the multi-vehicle panel is controlled through a setting which is part of FlyViewSettings. It defaults to visible.
* Add that as a setting in the Settings / Fly View / General ui
* If the setting in set to visible still only show the panel when multiple vehicles are available
* Rework the active vehicle selector in the toolbar. Make it look more like flight mode selection dropdown instead of a combo. In the expanded page for the dropdown, put the multi-vehicle panel on/off setting in there as well

How about that?

2025-01-15 09:29 UTC, demirciAhmet commented
> Here is what I would do:
> 
>     * The visibility of the multi-vehicle panel is controlled through a setting which is part of FlyViewSettings. It defaults to visible.
> 
>     * Add that as a setting in the Settings / Fly View / General ui
> 
>     * If the setting in set to visible still only show the panel when multiple vehicles are available
> 
>     * Rework the active vehicle selector in the toolbar. Make it look more like flight mode selection dropdown instead of a combo. In the expanded page for the dropdown, put the multi-vehicle panel on/off setting in there as well
> 
> 
> How about that?

So, you're suggesting we stick with something similar to the previous approach regarding the on/off point. But it might result in a loss of flexibility and make it harder to use?
 
Isn't this "while still allowing users to open and close it via swiping" approach more user friendly?

2025-01-15 20:00 UTC, DonLakeFlyer commented
My thinking was along the lines of you either use the panel or you don't use the panel. If you don't use the panel then you don't want stuff no matter how small cluttering things up. I was not thinking that you might hide/show the panel multiple times during the same flight. In that case, yes some quicker way to access it would be better. But I'm not sure if that an important use case to consider?

I don't want to create new paradigms for the UI unless they are really necessary. And then if something new is added it is added in a consistent way. For example if you can swipe this multi-vehicle thing off the screen. Then why can't you swipe the video thing off the screen when you don't need it and are just flying a single vehicle. If it's not a critical need then I'd rather have consistency in how things are done.

2025-01-16 14:10 UTC, demirciAhmet commented
> My thinking was along the lines of you either use the panel or you don't use the panel. If you don't use the panel then you don't want stuff no matter how small cluttering things up. I was not thinking that you might hide/show the panel multiple times during the same flight. In that case, yes some quicker way to access it would be better. But I'm not sure if that an important use case to consider?
> 
> I don't want to create new paradigms for the UI unless they are really necessary. And then if something new is added it is added in a consistent way. For example if you can swipe this multi-vehicle thing off the screen. Then why can't you swipe the video thing off the screen when you don't need it and are just flying a single vehicle. If it's not a critical need then I'd rather have consistency in how things are done.

Oh, I see what you mean now—that makes sense. I’ll probably complete the improvements tomorrow. Should I push the changes as a new commit for easier review, or rebase again and force push?

2025-01-17 18:14 UTC, DonLakeFlyer commented
The setting for the panel in the toolbar indicator should use the same wording as in Fly View Settings: "Enable Multi-Vehicle Panel". Also it should be in the expanded portion of the indicator which matches the usage of settings in indicators in all the other indicators.

2025-01-17 19:08 UTC, DonLakeFlyer commented
Took a look. Perfect, thanks. This is great new work. I'll merge once it passes CI.

2025-01-17 19:19 UTC, demirciAhmet commented
> Took a look. Perfect, thanks. This is great new work. I'll merge once it passes CI.

Glad to hear! Thank you too.

2025-01-17 22:05 UTC, DonLakeFlyer approved these changes

2025-01-17 22:06 UTC, merged