Remote id UI refactor
mavlink/qgroundcontrol pull request #12120
Opened 2024-11-21 17:06 UTC by bytesByHarsh

Description
-----------
- Update settings page for remoteID
- Update toolbar indicator for remoteID 

Test Steps
-----------

1) App Settings --> MockLink --> Start Mocklink
2) App Settings --> Remote ID

Related Issue
-----------
https://github.com/mavlink/qgroundcontrol/issues/12018

2024-11-21 17:11 UTC, bytesByHarsh commented
I have updated just the settings page currently, if the changes are ok then I'll remove them from the toolbar UI as well.

2024-11-25 19:26 UTC, DonLakeFlyer requested changes
I need to take another look at how validation errors are displayed since this border color changes stuff isn't really a ui standard in QGC. I'll create an issue for that and figure out whaat to do.

Other than the one change this all looks like. Fix that, and I'll merge.

2024-11-26 06:22 UTC, bytesByHarsh commented
> I need to take another look at how validation errors are displayed since this border color changes stuff isn't really a ui standard in QGC. I'll create an issue for that and figure out what to do.


@DonLakeFlyer So in the current UI should I completely remove the border color checks and changes?

2024-11-26 18:49 UTC, bytesByHarsh commented on src/UI/preferences/RemoteIDSettings.qml
> +                                _remoteIDManager.checkOperatorID(text)
I have corrected the variable and verified it with the toolbar code.

2024-12-02 17:18 UTC, merged