RadioComponentController fix for Custom builds
mavlink/qgroundcontrol pull request #9540
Opened 2021-03-18 07:03 UTC by mnumanuyar

Signed-off-by: numan.uyar <numan.uyar@titra.com.tr>

related to issue: #9539

2021-03-19 18:31 UTC, DonLakeFlyer commented
I assume you are doing this because you have an ArduPilot custom build?

Since the RadioComponentController implementation is common to both PX4 and ArduPilot the correct change is to move this to the FirmwarePlugin base class. Moving it to QGCApplication causes it to be compiled in even if you are not using either PX4 or ArduPilot firmwares which is incorrect.

2021-03-20 15:55 UTC, mnumanuyar commented
You are absolutely correct! 
I think FirmwarePlugin does not have a constructor, should I create one and then us it in PX4FirmwarePlugin and APMFirmwarePlugin, or is there a better way?

2021-03-20 17:10 UTC, DonLakeFlyer commented
Yes, create a constructor for FirmwarePlugin. I don't think you need to mod px4 or apm firmware plugin code to make it work,.

2021-03-22 11:55 UTC, mnumanuyar commented
It should be ok now

2021-03-23 17:41 UTC, DonLakeFlyer commented on src/FirmwarePlugin/FirmwarePlugin.cc
> +    qmlRegisterType<RadioComponentController>       ("QGroundControl.Controllers",                       1, 0, "RadioComponentController");
Can you pull the tabs out of here?

2021-03-23 17:41 UTC, DonLakeFlyer commented on src/FirmwarePlugin/FirmwarePlugin.h
> +    FirmwarePlugin ();
Also the extra space here to match coding style

2021-03-24 17:38 UTC, DonLakeFlyer requested changes
Should be all god after the minor spacing fixes

2021-04-05 15:42 UTC, DonLakeFlyer commented
@mnumanuyar Can you update?

2021-04-21 16:04 UTC, DonLakeFlyer commented
@mnumanuyar Can you update?

2021-05-04 20:00 UTC, merged

2021-05-17 11:27 UTC, mnumanuyar commented
sorry, I posted somewhere else but forget to put it also here. Unfortunately I am a little busy with work related stuff. I will probably have more time in 2-3 weeks.

2021-05-17 11:27 UTC, mnumanuyar commented
Also thank you for merging and care