Fix getting stuck when returning to the main screen while the parameter editor is open
mavlink/qgroundcontrol pull request #9850
Opened 2021-09-01 05:27 UTC by WTPENGUIN

Fix #9833 

https://user-images.githubusercontent.com/28136137/131616675-400e376d-ee9a-4a76-9f1e-a02741398797.mp4

2021-10-02 21:10 UTC, patrickelectric requested changes

2021-10-02 21:10 UTC, patrickelectric commented on src/QmlControls/QGCViewDialogContainer.qml
> +            else {
Else is unnecessary if inside the first if there is a return

2021-11-18 07:45 UTC, mortenfyhn commented
Fantastic! :rocket:

2021-11-18 10:41 UTC, mortenfyhn commented
I tested this myself and it certainly works! Would be great to get it merged.

2021-11-19 18:01 UTC, DonLakeFlyer commented
@WTPENGUIN Is there a reason why this was closed?

2021-11-19 21:58 UTC, WTPENGUIN commented
@DonLakeFlyer There was a request to change the code, so I thought I would close it and reopen it later.

2021-11-21 18:59 UTC, DonLakeFlyer commented
Ah, ok thanks.

2021-11-21 19:00 UTC, DonLakeFlyer commented
I re-opened since it fixes a critical bug. So might as well get it in. Not having the else is more a stylistic thing which to me can go either way. So I'll merge once it passes CI since I need this fix for stable.

2021-11-22 00:20 UTC, WTPENGUIN commented
@DonLakeFlyer The CI test is a bit weird. A test failure occurs on the Mock Link side, and I have never modified the code there.

2021-11-22 18:47 UTC, DonLakeFlyer commented
Hmm, there seems to be some flakiness in one of the unit tests. Looks completely unrelated to your change but re-running to be safe.

2021-11-22 20:47 UTC, WTPENGUIN commented
@DonLakeFlyer Oh, there seems to be no problem.

2021-11-22 22:14 UTC, DonLakeFlyer commented
Yup, thanks

2021-11-22 22:15 UTC, merged

2021-11-23 07:51 UTC, mortenfyhn commented
Great! Thanks @WTPENGUIN